// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9dibaNzLyFHR3uMKdksYdR1EDpdDvGSM',
    appId: '1:1012515500034:web:c099cfb948e8d638d8771b',
    messagingSenderId: '1012515500034',
    projectId: 'chat-app-882c3',
    authDomain: 'chat-app-882c3.firebaseapp.com',
    storageBucket: 'chat-app-882c3.firebasestorage.app',
    measurementId: 'G-EQV16C3GHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxS4wIUUCEPzo2QGMubYttYCOP73ld0_Q',
    appId: '1:1012515500034:android:221c7fe302a359c4d8771b',
    messagingSenderId: '1012515500034',
    projectId: 'chat-app-882c3',
    storageBucket: 'chat-app-882c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9bDip0HE3rXnB1pyeYdF8jglUaUu9zt4',
    appId: '1:1012515500034:ios:4c755c98ed686acfd8771b',
    messagingSenderId: '1012515500034',
    projectId: 'chat-app-882c3',
    storageBucket: 'chat-app-882c3.firebasestorage.app',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9bDip0HE3rXnB1pyeYdF8jglUaUu9zt4',
    appId: '1:1012515500034:ios:4c755c98ed686acfd8771b',
    messagingSenderId: '1012515500034',
    projectId: 'chat-app-882c3',
    storageBucket: 'chat-app-882c3.firebasestorage.app',
    iosBundleId: 'com.example.myChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9dibaNzLyFHR3uMKdksYdR1EDpdDvGSM',
    appId: '1:1012515500034:web:5c435139e89349d5d8771b',
    messagingSenderId: '1012515500034',
    projectId: 'chat-app-882c3',
    authDomain: 'chat-app-882c3.firebaseapp.com',
    storageBucket: 'chat-app-882c3.firebasestorage.app',
    measurementId: 'G-DMSEYKMBK2',
  );
}
